import type { CSSProperties } from 'react';

export const styles: { [key: string]: CSSProperties } = {
  layout: { display: 'flex', height: '100vh', overflow: 'hidden' },
  sidebar: { width: '250px', background: '#1f2937', color: '#fff', padding: '20px', overflowY: 'auto' },
  logo: { fontSize: '1.5rem', marginBottom: '2rem', fontWeight: 'bold' },
  menu: { listStyle: 'none', padding: 0 },
  menuItem: { padding: '10px 15px', borderRadius: '5px', marginBottom: '5px', transition: 'background 0.2s' },
  menuLink: { color: '#fff', textDecoration: 'none', display: 'flex', justifyContent: 'space-between' },
  badge: { background: '#ef4444', color: '#fff', borderRadius: '50%', padding: '2px 8px', fontSize: '0.75rem' },
  logoutBtn: { background: 'transparent', border: 'none', color: '#fff', cursor: 'pointer', fontSize: '1rem', width: '100%', textAlign: 'left' },
  main: { flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden' },
  header: { padding: '15px 20px', background: '#fff', borderBottom: '1px solid #e5e7eb', display: 'flex', justifyContent: 'space-between', flexShrink: 0 },
  headerRight: { display: 'flex', gap: '10px' },
  content: { flex: 1, padding: 0, overflow: 'auto' },
  loading: { display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100%' },
  dashboard: { height: '100%', display: 'flex', flexDirection: 'column', padding: '0', margin: '0' },
  dashboardGrid: { flex: 1, display: 'flex', flexDirection: 'column', gap: '10px', overflow: 'hidden', padding: '15px' },
  statsGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(120px, 1fr))', gap: '10px' },
  statCard: { background: '#fff', padding: '12px', borderRadius: '8px', boxShadow: '0 1px 3px rgba(0,0,0,0.1)', textAlign: 'center' },
  chartsRow: { display: 'flex', gap: '20px', flex: '1 1 auto', minHeight: '0' },
  chartBox: { flex: '1', background: '#fff', borderRadius: '8px', padding: '10px', boxShadow: '0 1px 3px rgba(0,0,0,0.1)', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  recentRow: { display: 'flex', gap: '20px', flexShrink: 0, height: '120px' },
  recentBox: { flex: 1, background: '#fff', borderRadius: '8px', padding: '10px 14px', boxShadow: '0 1px 3px rgba(0,0,0,0.1)', overflow: 'hidden' },
  recentItem: { fontSize: '0.9rem', padding: '4px 0', borderBottom: '1px solid #f3f4f6' },
  empty: { color: '#9ca3af', textAlign: 'center', padding: '10px 0' },
  pageNoPadding: { padding: 0, height: '100%', display: 'flex', flexDirection: 'column' },
  toolbarNoPad: { padding: '12px 16px', background: '#fff', borderBottom: '1px solid #e5e7eb', flexShrink: 0 },
  pageTitle: { margin: 0, fontSize: '1.5rem', fontWeight: '600' },
  toolbar: { display: 'flex', flexWrap: 'wrap', gap: '10px', marginTop: '10px' },
  tableWrapper: { flex: 1, overflow: 'auto', padding: '0' },
  table: { width: '100%', borderCollapse: 'collapse', background: '#fff', fontSize: '0.9rem' },
  pagination: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '12px 16px', background: '#fff', borderTop: '1px solid #e5e7eb', flexShrink: 0 },
  input: { padding: '10px', border: '1px solid #d1d5db', borderRadius: '6px', fontSize: '0.9rem', flex: 1, minWidth: '150px' },
  button: { background: '#3b82f6', color: '#fff', padding: '10px 20px', border: 'none', borderRadius: '6px', cursor: 'pointer', fontWeight: '500' },
  error: { color: '#ef4444', fontSize: '0.8rem', marginTop: '-5px', marginBottom: '10px' },
  smallBtn: { background: '#3b82f6', color: '#fff', padding: '4px 10px', border: 'none', borderRadius: '4px', cursor: 'pointer', marginRight: '5px' },
  modal: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,0.5)', display: 'flex', justifyContent: 'center', alignItems: 'center', zIndex: 1000 },
  modalContent: { background: '#fff', padding: '30px', borderRadius: '8px', width: '500px', maxHeight: '90vh', overflowY: 'auto' },
  notifItem: { padding: '15px', marginBottom: '10px', borderRadius: '8px', border: '1px solid #e5e7eb', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  reportCard: { background: '#fff', padding: '16px', borderRadius: '8px', boxShadow: '0 1px 3px rgba(0,0,0,0.1)' },
  reportItem: { padding: '6px 0', borderBottom: '1px solid #f3f4f6' },
  page: { padding: '20px', overflowY: 'auto', height: '100%' },
};

export const loginStyles: { [key: string]: CSSProperties } = {
  container: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '100vh',
    background: '#f3f4f6',
    padding: '20px',
  },
  box: {
    background: '#fff',
    padding: '40px',
    borderRadius: '12px',
    boxShadow: '0 8px 24px rgba(0,0,0,0.1)',
    width: '100%',
    maxWidth: '400px',
  },
  title: {
    fontSize: '2rem',
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: '8px',
  },
  subtitle: {
    fontSize: '1.2rem',
    textAlign: 'center',
    marginBottom: '24px',
    color: '#6b7280',
  },
  errorMessage: {
    background: '#fef2f2',
    color: '#ef4444',
    padding: '10px 14px',
    borderRadius: '8px',
    marginBottom: '16px',
    border: '1px solid #fecaca',
  },
  field: {
    marginBottom: '16px',
  },
  fieldError: {
    color: '#ef4444',
    fontSize: '0.8rem',
    display: 'block',
    marginTop: '4px',
  },
  input: {
    width: '100%',
    padding: '10px 12px',
    border: '1px solid #d1d5db',
    borderRadius: '6px',
    fontSize: '1rem',
    marginTop: '4px',
  },
  remember: {
    display: 'flex',
    alignItems: 'center',
    marginBottom: '20px',
  },
  button: {
    width: '100%',
    padding: '12px',
    background: '#3b82f6',
    color: '#fff',
    border: 'none',
    borderRadius: '6px',
    fontSize: '1rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'background 0.2s',
  },
  demo: {
    marginTop: '24px',
    padding: '12px',
    background: '#f9fafb',
    borderRadius: '8px',
    textAlign: 'center',
    fontSize: '0.9rem',
    color: '#6b7280',
  },
};